services:
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: sail
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    networks:
      - sail